# Generated by Django 3.2.12 on 2025-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des Unternehmens', max_length=200, verbose_name='Firmenname')),
                ('website', models.URLField(blank=True, help_text='Website URL des Unternehmens', null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, help_text='Hauptkontakt E-Mail', max_length=254, null=True, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, help_text='Haupttelefonnummer', max_length=20, null=True, verbose_name='Telefon')),
                ('street_address', models.CharField(blank=True, help_text='Straße und Hausnummer', max_length=255, null=True, verbose_name='Straße')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, null=True, verbose_name='Land')),
                ('industry', models.CharField(blank=True, help_text='Branche/Industriezweig', max_length=100, null=True, verbose_name='Branche')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 Mitarbeiter'), ('11-50', '11-50 Mitarbeiter'), ('51-200', '51-200 Mitarbeiter'), ('201-1000', '201-1000 Mitarbeiter'), ('1000+', '1000+ Mitarbeiter')], max_length=50, null=True, verbose_name='Unternehmensgröße')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen über das Unternehmen', null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('is_active', models.BooleanField(default=True, help_text='Ist das Unternehmen aktiv im System?', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
                'ordering': ['name'],
            },
        ),
    ]
